/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedLandingRouteImport } from './routes/_authenticated/landing'
import { Route as AuthenticatedKanaRouteImport } from './routes/_authenticated/kana'
import { Route as AuthenticatedGrammarRouteImport } from './routes/_authenticated/grammar'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandingRoute = AuthenticatedLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanaRoute = AuthenticatedKanaRouteImport.update({
  id: '/kana',
  path: '/kana',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrammarRoute = AuthenticatedGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/kana': typeof AuthenticatedKanaRoute
  '/landing': typeof AuthenticatedLandingRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/kana': typeof AuthenticatedKanaRoute
  '/landing': typeof AuthenticatedLandingRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/grammar': typeof AuthenticatedGrammarRoute
  '/_authenticated/kana': typeof AuthenticatedKanaRoute
  '/_authenticated/landing': typeof AuthenticatedLandingRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/change-password'
    | '/grammar'
    | '/kana'
    | '/landing'
    | '/roles'
    | '/users'
    | '/vocabulary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/change-password'
    | '/grammar'
    | '/kana'
    | '/landing'
    | '/roles'
    | '/users'
    | '/vocabulary'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/change-password'
    | '/_authenticated/grammar'
    | '/_authenticated/kana'
    | '/_authenticated/landing'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/_authenticated/vocabulary'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landing': {
      id: '/_authenticated/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof AuthenticatedLandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kana': {
      id: '/_authenticated/kana'
      path: '/kana'
      fullPath: '/kana'
      preLoaderRoute: typeof AuthenticatedKanaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grammar': {
      id: '/_authenticated/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthenticatedGrammarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedGrammarRoute: typeof AuthenticatedGrammarRoute
  AuthenticatedKanaRoute: typeof AuthenticatedKanaRoute
  AuthenticatedLandingRoute: typeof AuthenticatedLandingRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedGrammarRoute: AuthenticatedGrammarRoute,
  AuthenticatedKanaRoute: AuthenticatedKanaRoute,
  AuthenticatedLandingRoute: AuthenticatedLandingRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
