/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVocabularyRouteImport } from './routes/_authenticated/vocabulary'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedLandingRouteImport } from './routes/_authenticated/landing'
import { Route as AuthenticatedKanaRouteImport } from './routes/_authenticated/kana'
import { Route as AuthenticatedGrammarRouteImport } from './routes/_authenticated/grammar'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVocabularyRoute = AuthenticatedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandingRoute = AuthenticatedLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanaRoute = AuthenticatedKanaRouteImport.update({
  id: '/kana',
  path: '/kana',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrammarRoute = AuthenticatedGrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/kana': typeof AuthenticatedKanaRoute
  '/landing': typeof AuthenticatedLandingRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/grammar': typeof AuthenticatedGrammarRoute
  '/kana': typeof AuthenticatedKanaRoute
  '/landing': typeof AuthenticatedLandingRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vocabulary': typeof AuthenticatedVocabularyRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/grammar': typeof AuthenticatedGrammarRoute
  '/_authenticated/kana': typeof AuthenticatedKanaRoute
  '/_authenticated/landing': typeof AuthenticatedLandingRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vocabulary': typeof AuthenticatedVocabularyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/change-password'
    | '/grammar'
    | '/kana'
    | '/landing'
    | '/roles'
    | '/users'
    | '/vocabulary'
    | '/accounts/$id'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/change-password'
    | '/grammar'
    | '/kana'
    | '/landing'
    | '/roles'
    | '/users'
    | '/vocabulary'
    | '/'
    | '/accounts/$id'
    | '/accounts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/accounts'
    | '/_authenticated/change-password'
    | '/_authenticated/grammar'
    | '/_authenticated/kana'
    | '/_authenticated/landing'
    | '/_authenticated/roles'
    | '/_authenticated/users'
    | '/_authenticated/vocabulary'
    | '/_authenticated/'
    | '/_authenticated/accounts/$id'
    | '/_authenticated/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vocabulary': {
      id: '/_authenticated/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof AuthenticatedVocabularyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landing': {
      id: '/_authenticated/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof AuthenticatedLandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kana': {
      id: '/_authenticated/kana'
      path: '/kana'
      fullPath: '/kana'
      preLoaderRoute: typeof AuthenticatedKanaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grammar': {
      id: '/_authenticated/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof AuthenticatedGrammarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/_authenticated/accounts/$id': {
      id: '/_authenticated/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedGrammarRoute: typeof AuthenticatedGrammarRoute
  AuthenticatedKanaRoute: typeof AuthenticatedKanaRoute
  AuthenticatedLandingRoute: typeof AuthenticatedLandingRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVocabularyRoute: typeof AuthenticatedVocabularyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedGrammarRoute: AuthenticatedGrammarRoute,
  AuthenticatedKanaRoute: AuthenticatedKanaRoute,
  AuthenticatedLandingRoute: AuthenticatedLandingRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVocabularyRoute: AuthenticatedVocabularyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
