/**
 * import-grammar.ts
 *
 * Imports grammar data from local CSV files into the database.
 * Files are generated by: npm run scrape-grammar
 *
 * Usage:
 *   npm run import:grammar
 */

import * as fs from 'fs'
import {MikroORM} from '@mikro-orm/core'
import config from '../mikro-orm.config'
import {Grammar} from '../entities/Grammar'

// ─── Config ──────────────────────────────────────────────────────────────────
// All 5 levels from the J-O-S-H-L/grammar_dict source (grammar_points.json)

const FILES: {level: string; file: string}[] = [
  {level: 'N5', file: 'n5_full_sample.txt'},
  {level: 'N4', file: 'n4_full_sample.txt'},
  {level: 'N3', file: 'n3_full_sample.txt'},
  {level: 'N2', file: 'n2_full_sample.txt'},
  {level: 'N1', file: 'n1_full_sample.txt'},
]

// ─── CSV helpers ─────────────────────────────────────────────────────────────

/**
 * RFC-4180 compliant CSV field splitter.
 * Handles: semicolon delimiter, double-quote escaping (""), embedded semicolons.
 */
function splitCsvLine(line: string): string[] {
  const fields: string[] = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]

    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        // Escaped quote ( "")
        current += '"'
        i++
      } else {
        inQuotes = !inQuotes
      }
    } else if (ch === ';' && !inQuotes) {
      fields.push(current)
      current = ''
    } else {
      current += ch
    }
  }
  fields.push(current)
  return fields
}

function parseCsv(content: string): Record<string, string>[] {
  const lines = content.trim().split('\n')
  if (lines.length < 2) return []
  const headers = splitCsvLine(lines[0]).map((h) => h.trim())
  const rows: Record<string, string>[] = []

  for (let i = 1; i < lines.length; i++) {
    const values = splitCsvLine(lines[i])
    // Skip rows that don't have enough fields
    if (values.length < headers.length) continue
    const row: Record<string, string> = {}
    for (let j = 0; j < headers.length; j++) {
      row[headers[j]] = values[j].trim()
    }
    rows.push(row)
  }
  return rows
}

// ─── Clean text ─────────────────────────────────────────────────────────────

/**
 * Strips HTML tags and HTML entities from Bunpro-sourced fields.
 * Also removes literal "default" which is used as empty-field placeholder.
 */
function clean(text: string | undefined): string | undefined {
  if (!text) return undefined
  const s = text
    .replace(/<[^>]+>/g, '')       // strip HTML tags
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/\bdefault\b/gi, '')    // remove literal "default"
    .replace(/\s+/g, ' ')           // collapse whitespace
    .trim()
  return s === '' ? undefined : s
}

// ─── Deduplication key ───────────────────────────────────────────────────────

function dedupKey(gp: string, level: string): string {
  return `${level}::${gp}`
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function run() {
  const orm = await MikroORM.init(config)
  const em = orm.em.fork()

  // Load existing keys from DB for fast deduplication
  const existing = await em.find(Grammar, {})
  const existingKeys = new Set(existing.map((g) => dedupKey(g.grammarPoint, g.level)))
  console.log(`Existing grammar entries: ${existingKeys.size}`)

  let totalInserted = 0

  for (const {level, file} of FILES) {
    console.log(`\nReading ${file}...`)

    let raw: string
    try {
      raw = fs.readFileSync(file, 'utf8')
    } catch {
      console.error(`  ERROR: File not found — run 'npm run scrape:grammar' first`)
      continue
    }

    const rows = parseCsv(raw)
    console.log(`  ${rows.length} rows parsed`)

    let inserted = 0
    for (const row of rows) {
      const gp = clean(row.grammar_point)
      if (!gp) continue

      const key = dedupKey(gp, row.level || level)
      if (existingKeys.has(key)) continue

      const grammar = new Grammar()
      grammar.grammarPoint = gp
      grammar.meaning = clean(row.meaning) ?? ''
      grammar.level = row.level || level
      grammar.lessonNumber = row.lesson_number
        ? parseInt(row.lesson_number, 10)
        : undefined
      grammar.lessonTitle = clean(row.lesson_title)
      grammar.structure = clean(row.structure)
      grammar.structureDisplay = clean(row.structure_display)
      grammar.partOfSpeech = clean(row.part_of_speech)
      grammar.register = clean(row.register)
      grammar.about = clean(row.about)
      grammar.exampleJp = clean(row.example_jp_1)
      grammar.exampleEn = clean(row.example_en_1)
      grammar.synonyms = clean(row.synonyms)
      grammar.antonyms = clean(row.antonyms)
      grammar.meaningHint = clean(row.meaning_hint)

      em.persist(grammar)
      existingKeys.add(key)
      inserted++

      // Flush every 100 rows to keep memory manageable
      if (inserted % 100 === 0) {
        await em.flush()
        em.clear()
      }
    }

    await em.flush()
    em.clear()
    totalInserted += inserted
    console.log(`  Inserted ${inserted}`)
  }

  console.log(`\n✅ Total inserted: ${totalInserted}`)
  await orm.close(true)
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
